---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    yum:
      name: httpd
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: httpd
      state: started
  - name: Enable services for automatic start
    service:
      name: "{{ item }}"
      enabled: yes
    with_items:
      - httpd
  - name: Enable ports on the list
    firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled
    notify:
      - Restart firewalld
  handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
