---
- name: Manage public ports with firewalld ansible module 
  hosts: "*"
  gather_facts: no
  become: true
  tasks:
    - name: Enable ports on the list
      firewalld:
        zone: public
        port: 80/tcp
        permanent: true
        state: disabled
      notify:
        - Restart firewalld
  handlers:
    - name: Restart firewalld
      service:
        name: firewalld
        state: restarted
