---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository cache (CentOS)
    tags: always
    yum:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repository cache (Linux Mint)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Linux Mint"

- hosts: all
  become: true
  roles:
    - base

- hosts: web_servers
  become: true
  roles:
    - web_servers 

- hosts: db_servers
  become: true
  roles:
    - db_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

- hosts: workstations
  become: true
  roles:
    - workstations
